### ISSUE TITLE
Make Chat works

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1101]
Core features must work, right ?
>Chat doesn’t reflect what you have in memories. A user would like to chat with their past conversations, which currently isn’t possible.

\- by @mdmohsin7 

**what**: Chat have to reflect what users have in their memories.

**Comment by beastoin** [comment]
Beats1310 — Yesterday at 10:39 PM
I have a question: why is the latency for RAG in Omi app? 2 years ago it would be mind-blowing but right now, it's kinda slow to respond

Salman — Today at 7:23 AM
~20 sec to get an answer back and memories shown below the response are not even for the correct time period.

**Comment by beastoin** [comment]
@josancamon19 bruh pls help with chat ~ feel free to mention your related tickets

**Comment by josancamon19** [comment]
Whats the time response requirement?

I want to target most of this questions, is this accurate with what it should be able to respond?

![Image](https://github.com/user-attachments/assets/3b9db76f-3dd6-4a4a-9d6f-b9641bf0ec92)

**Comment by josancamon19** [comment]
going to use structured data search + langgraph for navigating multiple cases

**Comment by beastoin** [comment]
response time: 1,2,3,4,5; 5s, faster is better, is it possible? @josancamon19

**Comment by beastoin** [comment]
> going to use structured data search + langgraph for navigating multiple cases

great! feel free to share me more 😌

**Comment by josancamon19** [comment]
Stuff changing rn.
1. The search will not be main vector retrieval (instead will default to it if nothing found with first method), not useful with this kind of all possibilities search, neither with bad transcript data.
2. Instead the main search will be a "deterministic" search for each use case, extracting structured data from the transcript. The extracted information will contain the following fields.
```
class ExtractedInformation(BaseModel):
    people_mentioned: List[str] = Field(
        default=[],
        description='Identify all the people names who were mentioned during the conversation.'
    )
    topics_discussed: List[str] = Field(
        default=[],
        description='List all the main topics and subtopics that were discussed.',
    )
    entities: List[str] = Field(
        default=[],
        description='List any products, technologies, places, or other entities that are relevant to the conversation.'
    )
    dates: List[date] = Field(
        default=[],
        description=f'Extract any dates mentioned in the conversation. Use the format YYYY-MM-DD.'
    )
```
3. This information will be stored in the vectors metadata.
4. Topics search will be made by asking an LLM, "find the entities, dates, topics, people that might be of interest in order to answer this question", with that we will do vector search + simple reranking by matching count.
5. Langraph is also being introduced for simplicity and further iteration, we can add tools, branches, or any other use cases very simply.



![Image](https://github.com/user-attachments/assets/b3d7fcda-298b-4607-aeb0-11e63a517413)

**Comment by beastoin** [comment]
how's it going bro? any help wanted ?

**Comment by beastoin** [comment]
bro, just read your changes https://github.com/BasedHardware/Omi/compare/v1.0.44+162-mobile-cm...80b227 and that's great! please:
1/ provide some benchmark
2/ push it to the production (take your time)
3/ monitor over the next 2 weeks, weekly retrospectives, then propose enhancements or fixes needed.

have a nice weekend 😌

@josancamon19
