### ISSUE TITLE
Search in conversations (ex memories)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1433]
Need to add search capability in conversations page (ex. memories)

**Comment by mdmohsin7** [comment]
I can restore the old search bar we used to have for memories (but that would not look much better because of too many options on the home screen) or can make the experience more better by having a lot better search and filter for conversations by moving them to a new screen. Lmk what you'd prefer
![Home](https://github.com/user-attachments/assets/4fd28ce3-bf6c-4ab1-8d39-9982ae4b489b)
![Conversations](https://github.com/user-attachments/assets/d32ae5d9-1a73-4905-a5fc-b5e059d96441)

**Comment by josancamon19** [comment]
Yes!

**Comment by beastoin** [comment]
for your question, i would prefer restoring the search bar then open the new search page when enter the search. 

however, the most important thing is not how it looks but what problem that feature is intend to solve? 

we have the chat feature with full customization cabilities - graph, rag, llm. remember?

my suggestion is instead of focusing on the UI/UX. let's first figure out the problem or, at least the real needs of the users, then clarify it - the solution should come afterward.

@mdmohsin7 hope that help.

**Comment by kodjima33** [comment]
Why is this still not done? @mdmohsin7

**Comment by mdmohsin7** [comment]
> Why is this still not done? @mdmohsin7

Waiting for Thinh's review
