### ISSUE TITLE
"reconnecting" issue

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1474]
## Issues
- [x] https://github.com/BasedHardware/omi/issues/1428
- [x] https://github.com/BasedHardware/omi/issues/1261
- [x] the no internet alerting is so annoying - look! my internet connection is still good. ... https://github.com/BasedHardware/omi/issues/1474#issuecomment-2516701136

**Comment by beastoin** [comment]
https://github.com/BasedHardware/omi/issues/1428

**Comment by beastoin** [comment]
the no internet alerting is so annoying - look! my internet connection is still good.

![Image](https://github.com/user-attachments/assets/ce0fa0de-8a3d-40cc-b3ca-646dbd22c879)

**Comment by beastoin** [comment]
@nquang29 hey babe please take a look at this ticket. i need your experiences with your current friend device. focus on the reconnecting issue. try with dev env and lmk your finding.

 ![Image](https://github.com/user-attachments/assets/150f7d35-4d89-4e18-aa21-a77a2d1422da)

**Comment by mdmohsin7** [comment]
Spent around 2-3 hours trying to understand, debug and test and this is what I found:
- Deepgram sends close message which causes the socket to disconnect and then reconnect, hence the reconnecting.
1- https://github.com/orgs/deepgram/discussions/508#discussioncomment-7996305
2- https://developers.deepgram.com/docs/troubleshooting-websocket-data-and-net-errors-when-live-streaming-audio?utm_source=error_msg&utm_medium=api#troubleshooting-1011---net-0001-websocket-errors
    When I send the keep alive message every 10 seconds to deepgram, I hardly see any connection close from deepgram/backend side and the connection stays for a long duration
     <img width="705" alt="Screenshot 2024-12-19 at 5 56 52 PM" src="https://github.com/user-attachments/assets/72b67dcd-38d8-4a6a-a233-3af57328cfb3" />

- The reconnection logic might be a bit flawed in the app side, every time there's a close message, the socket connection and disconnection happens twice, and the below line seems to be the culprit
https://github.com/BasedHardware/omi/blob/e107dbe2e1cb9048ec2a3c7ff826b8a4e3e60cf6/app/lib/services/sockets.dart#L55

   Without commenting the above line:
    <img width="515" alt="Screenshot 2024-12-19 at 2 00 36 PM" src="https://github.com/user-attachments/assets/e0aee7c1-009d-4805-b3c4-acc94796ab28" />
  With commenting the above line:
   <img width="515" alt="Screenshot 2024-12-19 at 2 01 03 PM" src="https://github.com/user-attachments/assets/a1367a2e-43ce-4b29-8eef-420986eee0cb" />
   
@beastoin

**Comment by beastoin** [comment]
lets go with keep-alive every 20s. to prevent the bad effect on the network high load. ping message might come a bit late.

@mdmohsin7

**Comment by beastoin** [comment]
also could you pls check the https://github.com/BasedHardware/omi/issues/1474#issuecomment-2516701136 ? @mdmohsin7

**Comment by mdmohsin7** [comment]
> lets go with keep-alive every 20s. to prevent the bad effect on the network high load. ping message might come a bit late.

Alright, Let me open the PR with this @beastoin

**Comment by mdmohsin7** [comment]
> also could you pls check the [#1474 (comment)](https://github.com/BasedHardware/omi/issues/1474#issuecomment-2516701136) ? @mdmohsin7

Yes will do that separately, I guess I know the issue and we might have to change the package we depend on for the connectivity status

**Comment by mdmohsin7** [comment]
Did some research and testing to figure out why the socket is actually closed. The current `keepalive: true` is enough to keep the socket open and skip the 12sec close. The `keepalive` option will automatically send a keep alive message every 10 seconds, so we don't actually have to do it manually.
https://developers.deepgram.com/docs/audio-keep-alive#what-is--thekeepalive-message

Test results:
- Dev deployment: Socket closed exactly every 290-300 seconds when there's no speech. This was continues for 4-5 times. The dev deployment only has 1 instance running
- Prod deployment: Socket closed at around 14-15 minutes when there's no speech. This was twice, on the 3rd attempt it was more than 15 mins (I guess because it picked some audio?). The prod deployment has minimum 2 instances, add to that there are atleast 2-3 people using the device at the same time (based on the logs)
- Local deployment: Socket did not disconnect at all. Disconnect happened after like 22 minutes on 2nd attempt/ Single instance with only one user, no resource issues

Makes me think is the issue really with deepgram or the available resources? Most of the people who report the connectivity issue use the device during the peak US hours. If the issue would have been with deepgram, it should be persistent during all the hours (which isn't the case as can be seen from the above tests)

@beastoin

**Comment by beastoin** [comment]
CR Dev:
---
 <img width="811" alt="Screenshot 2024-12-23 at 10 52 14" src="https://github.com/user-attachments/assets/a2f5c2e4-8b87-4c02-92af-ac7b653e7b29" />

CR Prod:
---
<img width="812" alt="Screenshot 2024-12-23 at 10 52 06" src="https://github.com/user-attachments/assets/a468b6be-9f6c-4398-8e84-3f63ddb20e8e" />

During the high load time: the no reason the CR instance will be stopped because CR is designed to scaling out without stopped the instance.

01 more question: when does the app force close the socket ?

@mdmohsin7 super close man.

**Comment by mdmohsin7** [comment]
> when does the app force close the socket ?

1. When a device is connected
2. When the device is disconnected and a new device is connected
3. When the language is changed
4. When the speech profile is started
5. When the user navigates back from the speech profile screen (after starting it)

@beastoin

**Comment by mdmohsin7** [comment]
So it has to do with the request timeout? What if we send the keepalive message when we are close to the request timeout duration? @beastoin
