### ISSUE TITLE
Automate development and production releases [$700]

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#298]
**Is your feature request related to a problem? Please describe.**
Use Github Actions + Fastlane to automate releases to alpha and production channels. When pushing to development branch, it should push a version to Testflight, and for android it should push an alpha version, when pushing to production, it should create draft releases for each platform.

**Describe the solution you'd like**
When someone pushes to `development` or `main`, it should do what mentioned above.

**Describe alternatives you've considered**
CircleCI, and others.

**Comment by pratikbaid3** [comment]
Hi. I'd like to work on this task. 
Are you set on using fastlane? Or does codemagic work for you as well?

**Comment by vinayshankardubey** [comment]
Hi I am working on it, I am using Github Action

**Comment by pratikbaid3** [comment]
@josancamon19 any chance you can assign the tasks that are already being worked on. This will prevent engineering waste. Thanks.

**Comment by vinayshankardubey** [comment]
> @josancamon19 any chance you can assign the tasks that are already being worked on. This will prevent engineering waste. Thanks.

Yes @josancamon19  , @pratikbaid3 is right

**Comment by josancamon19** [comment]
Assigned to [vinayshankardubey](https://github.com/vinayshankardubey) rn, please keep posting updates

**Comment by TekExplorer** [comment]
If this doesn't get done, I'd be willing to make my own PR, but I wont start unless I'm asked to.
I'm the kind of person to make it super clear, so you'll know exactly what secrets to set in the repo.
Just let me know.

**Comment by vinayshankardubey** [comment]
Thanks @josancamon19 I am working on it

**Comment by vinayshankardubey** [comment]
Hi @josancamon19 ,

Hope you are doing well. As you have assigned me this task, finally I have implemented this functionality.

Now I'm able to create build, APK for android and IPA for iOS.after every push request on main branch.
Currently this is generating debug build for android, for creating release build I need **upload-keystore.jks**  file which is not available in the project file.

After this my plan is, Please provide credentials and make plan to deploy build directly on "Play Store" after build creation.

Please find below screenshots for check my work progress and also you can check my repo from here :  https://github.com/vinayshankardubey/Friend

![image](https://github.com/BasedHardware/Friend/assets/59216953/076d7d82-c33b-41c2-85a8-d1475b22f328)

**Comment by vinayshankardubey** [comment]
![image](https://github.com/BasedHardware/Friend/assets/59216953/0a4973a6-e115-443b-aadc-375853e71b89)

**Comment by raymondyegon** [comment]
> Hi @josancamon19 ,
> 
> Hope you are doing well. As you have assigned me this task, finally I have implemented this functionality.
> 
> Now I'm able to create build, APK for android and IPA for iOS.after every push request on main branch. Currently this is generating debug build for android, for creating release build I need **upload-keystore.jks** file which is not available in the project file.
> 
> After this my plan is, Please provide credentials and make plan to deploy build directly on "Play Store" after build creation.
> 
> Please find below screenshots for check my work progress and also you can check my repo from here : https://github.com/vinayshankardubey/Friend
> 
> ![image](https://private-user-images.githubusercontent.com/59216953/340975479-076d7d82-c33b-41c2-85a8-d1475b22f328.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODU0NTMsIm5iZiI6MTcxODc4NTE1MywicGF0aCI6Ii81OTIxNjk1My8zNDA5NzU0NzktMDc2ZDdkODItYzMzYi00MWMyLTg1YTgtZDE0NzViMjJmMzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4MTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmY2YyOWNkYTkxNTNlOWQ4ZjM5NzJkODI0MGZjZGE3ZDJjZTMyNTRlNjkyYzRhNmE5NDYwMzk0NGIwODliNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4v5iM3dbtWBXcxA_K5UrihBBOf3yV20E_CMNLTAhg0s)

Please create a PR as suggest for use to be able to give feedback from there

**Comment by vinayshankardubey** [comment]
> Please create a PR as suggest for use to be able to give feedback from there

Sure @raymondyegon ! 

But write now this functionality is not completed please provide upload-keystore.jks so I can create release build for Android also, through CI/CD.Right now this code is on my github repo which I have forked from real project.

Please just guide me how can I put my functionality on real project because I also need access of real project to create TOKEN key which is needed at the time or running action, you can also create this.

I am creating PR and Guide also.

Thanks. @josancamon19

**Comment by josancamon19** [comment]
Please send me a DM on discord `@josancamon19` I'll share the jks key there, the key has to go as a secret btw, so that it is not exposed.

**Comment by vinayshankardubey** [comment]
> Please send me a DM on discord `@josancamon19` I'll share the jks key there, the key has to go as a secret btw, so that it is not exposed.

@josancamon19 Please check just sent hi by vinayshankardubey

**Comment by josancamon19** [comment]
@vinayshankardubey Please keep posting updates, happy to help if you have any issues, and it'd also help if you create a Draft PR

**Comment by vinayshankardubey** [comment]
Hi Team,

I have just created a push request in development branch.
Right now I have set this action will perform on push request on "main branch" and pull and push request on "development"

It's working properly at my end now we need to test it at real project.

Please take pull request of "development branch" but before pull request please help me to add two secret's on project "Secrets and Variable" section.


1. Secret TOKEN :  Make sure it name should be "TOKEN"
2. upload-keystore.jks in Base64 format : I am using this because of security purpose generate bas64 format of upload-keystore.jks and add that key in secret with the name "SECRET_JKS"

Please help me to add these two dependencies then you can test it and please don't forget to give me feedback and suggestions if any.


Thanks @josancamon19 @kodjima33 @raymondyegon 


![image](https://github.com/BasedHardware/Friend/assets/59216953/b411c80a-0500-463e-b748-60efbd6dc4ea)

**Comment by vinayshankardubey** [comment]
Hi Team,

Can you please review my PR and Let me know feedback's and suggestion's so that I can complete my work.

Thanks
 @josancamon19

**Comment by vinayshankardubey** [comment]
Hi Team,

Today I am going to integrate Fastlane.

Thanks.

**Comment by vinayshankardubey** [comment]
Hi Team,

I have implemented Fastlane. Just going for a final try But for making release on testflight and play store I need below credetials for configure in Appfiles for both cases.

iOS :
app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
apple_id("[[APPLE_ID]]") # Your Apple Developer Portal username

itc_team_id("[[XXXXX]]") # App Store Connect Team ID
team_id("[XXXXX]]") # Developer Portal Team ID

Android :
Service Account JSON file: This file contains the credentials for your Google Play Developer API service account.


So please provide me credential so that I can head for next process.

Thanks

**Comment by vinayshankardubey** [comment]
Hi Team,

I have completed my fastlane integration for iOS and you can see , uploaded a testflight build also ....but it's working on my pc same functionality is not working with github actions.....I need some help ...Who can help me with xCode with Github Action..

and @josancamon19 please check discord.just dm you...I need some help

**Comment by vinayshankardubey** [comment]
Hi Team,

Still I am waiting please help me.

**Comment by vinayshankardubey** [comment]
Hi Team,


After a long R&D finally I have completed fastlane implementation for iOS.
now when I am making push request on development it's deploying a testflight build within 5-10 minutes.

for Android work is also completed at my end but still I am waiting for service account json key.
I have also admin access of google play console but only Account Holder can generate this key (https://devjorgecastro.medium.com/how-to-deploy-your-android-app-to-the-internal-track-in-the-play-store-console-using-fastlane-4f66efdabc12)

please provide me this json file so that I can perform task on android also.

Thanks @josancamon19 @kodjima33

**Comment by legut2** [comment]
Use codemagic.io

**Comment by vinayshankardubey** [comment]
Hi Team,

Still I am waiting for json file..
@josancamon19 @kodjima33

**Comment by vinayshankardubey** [comment]
Hi Team,

Can you please, reply me.So that I can complete this task.
@kodjima33 @josancamon19

**Comment by josancamon19** [comment]
Moved to other task using codemagic.io
