### ISSUE TITLE
Speech Profiles [Part 3]

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#388]
**Is your feature request related to a problem? Please describe.**
Assigning names to speakers during conversations would be step 1, like plaud does.

One step further, is to be able to train speech models from those samples selected, so next time the person get's assigned automatically.

https://github.com/BasedHardware/Friend/assets/18078879/91f25ebf-5fe6-44d7-88da-106b1d72ea37

**Comment by johnmccombs1** [comment]
I would suggest that we take a phased approach on this.

Phase 1 (speaker embedding comparison):
- Multiple Individual Speech Embeddings: I've attempted to average embeddings across a set of speaker embeddings, and it does seem to do relatively well when the spoken voice sounds similar to the speaker embeddings. The problem is that voices tend to vary quite a bit throughout a day, and sometimes even in the same conversation. So using a single averaged embedding isn't as reliable as several individual embeddings. Also, creating a speaker profile from a set of statements all at the same time tend to all sound very similar (at least mine have). I would suggest a dumb version of this is simply to allow saving multiple speaker embeddings that can be recorded as needed, and have the algorithm perform a cosine similarity on each individual embedding to find the highest score. I've found that for my embeddings so far, a score of 0.65 and above very closely matches my voice. Also, once we decide on the best speech embedding library, it would be ideal to go ahead and convert these to numpy arrays that are saved to disk so you don't have to spend processing time to convert them each time.
- A better version of this would be to allow in the interface for voice segments in the transcription to be converted into speech embeddings. The benefit to this is that it would allow you to easily add new speakers as well because you wouldn't need them to do any special recording, you simply take the recording you already have and save it to the profile.
- Another improvement would potentially be to compare saved speaker embeddings that have highly aligned cosine similarity scores and average them so that you can reduce the number of comparisons needed during speaker comparison.
- I've modified it on my local server and in the app already, but I think we should go ahead and modify the code to support speaker ids as strings instead of speaker ids as ints. Or add a new field for this purpose.
- It could would be nice to be able to enable speaker similarity scores to be saved alongside segments so you can easily determine which segments of a voice are the least similar so you know which ones to add to a speaker profile to provide a more robust profile. For example, currently I look for any that are below a 0.61 similarity score and add them to the server to be converted to an embedding. **I've attached a version of how I'm currently doing this so you can see how close the similarity matching is for my voice. When I was using just the speaker profile from the questions it was scoring around 0.55-0.7. Now it averages much higher after adding 3-4 additional profiles that I found didn't match those profiles as well.**
![IMG_313E1A98111D-1](https://github.com/user-attachments/assets/74455975-3aa7-4d7c-bb2d-bd25427a77d7)

Phase 2 (fine tuning):
- My limited understanding is that fine tuning an embedding model to match voices is much better at speaker identification than embedding comparison. The benefit to some of the suggestions in phase 1 are that if the interface makes it really easy to create new speakers and add profiles from the transcription itself, it would likely be very easy once you have enough recordings to submit these to a server for fine tuning. This would obviously create more storage on the server, but it would also allow this system to become one of the most accurate diarization systems available.

Phase 3 (Personal VAD):
- I haven't tested this myself, but you can view a research paper on it here https://arxiv.org/abs/1908.04284. The general idea is that training a VAD on a single voice can be more accurate at detecting that voice with a very small model, and as a result they suggest it could be much more usable for mobile devices. They also suggest that the model they used was able to detect non-speech, target-speaker speech, and non-target-speaker speech. If it's true that you can do this with a highly effecient model, then you should be able to accomplish two additional things. 1) Only listen for the speaker's voice (which is what their use case was meant for) and would allow users to turn this setting on and not have to worry about sending a lot of audio to the cloud, but also allow people to avoice violating a law by recording other people's voices. 2) Use a much more efficient voice model to handle voice detection on device (again assuming they are correct that this is much more efficient) so you don't waste so much bandwidth sending it to the cloud.

**Comment by johnmccombs1** [comment]
Also, I haven't tested SpeechBrain yet. I've been using speakerverification_en_titanet_large from Nvidia Nemo. There may not be much of a difference, but thought I would mention it in case it's helpful. Also, here is some quick code I'm using to store the embeddings by speaker:

```
def load_speaker_profile_embeddings():
    base_folder_path = f"_speaker_profiles/{self.uid}/"
    self.speaker_profile_embeddings = {}

    for speaker_name in os.listdir(base_folder_path):
        speaker_folder_path = os.path.join(base_folder_path, speaker_name)
        wav_folder_path = os.path.join(speaker_folder_path, "archive_wavs")
        embedding_folder_path = os.path.join(speaker_folder_path, "embeddings")

        os.makedirs(wav_folder_path, exist_ok=True)
        os.makedirs(embedding_folder_path, exist_ok=True)

        for file_name in os.listdir(speaker_folder_path):
            if file_name.endswith('.wav'):
                file_path = os.path.join(speaker_folder_path, file_name)
                embedding, _ = self.speaker_embedding_model.infer_file(path2audio_file=file_path)
                
                # Save the embedding
                embedding_file_path = os.path.join(embedding_folder_path, f"{file_name}.npy")
                np.save(embedding_file_path, embedding.cpu().numpy())

                # Move the wav file to archive
                archived_wav_path = os.path.join(wav_folder_path, file_name)
                os.rename(file_path, archived_wav_path)

        # Load embeddings
        self.speaker_profile_embeddings[speaker_name] = []
        for embedding_file in os.listdir(embedding_folder_path):
            if embedding_file.endswith('.npy'):
                embedding_path = os.path.join(embedding_folder_path, embedding_file)
                embedding = np.load(embedding_path)
                self.speaker_profile_embeddings[speaker_name].append(torch.tensor(embedding, device=self.device))

    return self.speaker_profile_embeddings
    
    def set_speaker_segments(self, segments: dict, audio: np.ndarray, sample_rate=16000):
    print('classify_segments')
    if not self.speaker_profile_embeddings:
        for segment in segments:
            segment['is_user'] = False
        return segments

    def process_single(i, segment, segment_audio):
        highest_similarity_score = 0
        best_speaker_embedding = None
        best_speaker_name = None
        for speaker_name, speaker_embeddings in self.speaker_profile_embeddings.items():
            for speaker_embedding in speaker_embeddings:
                similarity_score = self.speaker_similarity_score(speaker_name, speaker_embedding, segment_audio)

                if similarity_score > highest_similarity_score:
                    highest_similarity_score = similarity_score
                    best_speaker_embedding = speaker_embedding
                    best_speaker_name = speaker_name  # Assign to the speaker's name

        if highest_similarity_score >= 0.65:
            segment['is_user'] = (best_speaker_name == "Me")
            segment['speaker'] = "SPEAKER_" + best_speaker_name
        else:
            segment['is_user'] = False
            self.save_speaker_segment(segment_audio, segment, sample_rate, highest_similarity_score)
        
        segment['text'] += f" [{math.floor(highest_similarity_score * 100) / 100:.2f}]"

        speaker = "SPEAKER_Me" if segment.get('speaker') == "Me" else segment.get('speaker', 'SPEAKER_00')
        text = segment.get('text', '')
        print(f"{speaker}: {text}")
        

    for i, segment in enumerate(segments):
        segment_audio = audio[int(segment['start'] * sample_rate):int(segment['end'] * sample_rate)]
        process_single(i, segment, segment_audio)
        
    print('Speaker classification completed')
    return segments

def speaker_similarity_score(self, speaker_name, speaker_embedding, segment_audio):
    segment_embedding, _ = self.speaker_embedding_model.infer_segment(segment_audio)

    speaker_emb_1d = speaker_embedding.squeeze()
    segment_emb_1d = segment_embedding.squeeze()
    # Length Normalize
    X = speaker_emb_1d / torch.linalg.norm(speaker_emb_1d)
    Y = segment_emb_1d / torch.linalg.norm(segment_emb_1d)
    # Score
    similarity_score = torch.dot(X, Y) / ((torch.dot(X, X) * torch.dot(Y, Y)) ** 0.5)
    similarity_score = (similarity_score + 1) / 2
    print(f'Similarity score ({speaker_name}): {similarity_score.item():.4f}')

    return similarity_score
```
