### ISSUE TITLE
Finish setting up OTA updates for firmware. ($200)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#505]
**Is your feature request related to a problem? Please describe.**
From the app I should be able to update to new firmware versions.

**Describe the solution you'd like**
There should be a device settings in the app, that determines current firmware vs somewhere hosted maybe github, and tells if there's a new firmware version available.

Then should download that zip file, and use dfu.dart (which already works) to do the firmware restart on the device for the user.

**Additional context**
`dfu.dart` was commented, because the dependency was causing building issues for iOS and android (this should be fixed too)

**Comment by mdmohsin7** [comment]
To manage and pull versions, we could certainly use the releases API, but that would require us to maintain releases properly.

https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release

The other option could be to use something like Firebase (since we already have it integrated)

**Comment by beastoin** [comment]
@mdmohsin7 does it still work ?

**Comment by mdmohsin7** [comment]
Yes it does @beastoin with dk1. If the dk2 firmware supports OTA updates, then I can make some changes to the endpoint to support dk2 releases as well

**Comment by beastoin** [comment]
i see https://github.com/BasedHardware/omi/issues/1393
