### ISSUE TITLE
[Friend V2] Simulate Haptics with Speaker ($500)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#573]
**Is your feature request related to a problem? Please describe.**

Through speakers simulate haptics and vibration.

**Comment by pmb2** [comment]
I can handle this one 😄

**Comment by kevvz** [comment]
I'm unsure if this can be done. The "low tone" vibrations which could simulate haptics get distorted since the speak is kinda low quality. Basically, instead of a strong vibration you get an annoying squeak which doesn't vibrate. I think it will be easier to just attach a haptic motor instead. It makes everyone's life easier.

**Comment by josancamon19** [comment]
Speaker was set, but haptics simulation was impossible.
