### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by j3sk0** [BasedHardware/omi#747]
Hi it would be nice if you could change the language of the result in my case in German

**Comment by ccjeff** [comment]
+1. Can we have some kind of custom API using gpt3.5 to translate the language? I'd love to look into it but also wonder if anyone has been working on multi-lingual support

**Comment by j3sk0** [comment]
Shouldn't you just tell the prompt/workflow to write it in German at the end or use the variable from the language settings in the app user settings?

**Comment by neooriginal** [comment]
+1 aswell, if anyone builds the app infrastructure i would be willing to translate everything

**Comment by josancamon19** [comment]
Guys @j3sk0 @ccjeff @j3sk0 
It should be an easy fix, the problem I'm worried is how many edge cases would this cause.

Should be going here https://github.com/BasedHardware/Friend/blob/d63da62a15a89417d1741f1c6b0cade315852d6f/backend/utils/llm.py#L74

And instead of ```Your task is to provide structure and clarity to the recording transcription of a conversation.
        The conversation language is {language_code}. Use English for your response.``` "Use {language_code} for your response.

If one of you would like taking a look, and stress test that in a few languages, happy to merge that PR.

**Comment by j3sk0** [comment]
Thank you very much for your answer, I hope someone who has more experience than me will implement it and share instructions with me.

**Comment by j3sk0** [comment]
Thank you very much for your answer, I hope someone who has more experience than me will implement it and share instructions with me.
