### ISSUE TITLE
An ability to change link and add a self-hosted backend inside of an app

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#842]
**Is your feature request related to a problem? Please describe.**
Some enterprise users (Salman's friends in Salesforce) might want to use the app but only with a self-hosted backend. Current app allows to self-host backenbd but will also require self-hosted mobile app which people dont want 

**Describe the solution you'd like**
An ability to change link to a self-hosted backend inside of an app in settings. 

**Describe alternatives you've considered**
Generate private key

**Comment by asadbekdev** [comment]
Login-based Configuration:

Instead of directly inputting a backend URL, users log in with their enterprise credentials.
The app fetches the correct backend configuration based on the user's organization.
Pro: Centralized management of backend configurations.
Con: Requires more complex backend infrastructure to manage configurations.

Deep Linking: 

Create a custom URL scheme for your app (e.g., myapp://configure?backend=https://example.com).
Enterprises can send these links to their users via email or secure channels.
Pro: Easy to distribute and can be updated remotely.
Con: Requires handling deep links in the app and potential security considerations.

**Comment by josancamon19** [comment]
You can't have a self hosted backend without a self hosted app, as the authentication is e2e, they would have to run their own app. After discussions with salman, this doesn't seem like the reason for them not to use it.

Would require many changes for this to work without any proof of need, so closing, this is not planned.

**Comment by Rahulsharma0810** [comment]
Please Consider — @mdmohsin7  @josancamon19 

The "e2e auth" blocker cited in the closing comment is already solved in the codebase itself.

The actual blockers for self-hosted backend without a self-hosted app:

1. Firebase project mismatch — the app's tokens are signed for Omi's Firebase project, so a different backend rejects them. But the backend already has LOCAL_DEVELOPMENT=true which bypasses this entirely (endpoints.py). Any self-hoster can enable this.

 2. Flutter TLS — dart:io uses BoringSSL which ignores the iOS system certificate store, so self-signed certs for api.omi.me don't work even if trusted at the OS level. This is the real blocker — and it only exists because the URL is hardcoded.

The fix is already 90% done in the codebase:

```
  env.dart already has:
  static String? _apiBaseUrlOverride;

  static void overrideApiBaseUrl(String url) {
    _apiBaseUrlOverride = url;
  }


  static String? get apiBaseUrl => _apiBaseUrlOverride ?? _instance.apiBaseUrl;
```

Env.overrideApiBaseUrl() exists but is never exposed in the UI. Adding a single text field in Developer Settings that calls this method is the entire change needed. The infrastructure is already there.

Why this matters:
  - Users self-hosting to avoid transcription minute limits have to maintain a full fork of the iOS app just to change one URL
  - Every upstream update requires a manual merge + rebuild + re-sideload
  - Enterprise users (the original motivation for this issue) face the same friction at scale

  Suggested minimal implementation:
  - Developer Settings → "Custom Backend URL" text field
  - On save: call Env.overrideApiBaseUrl(url) + persist to SharedPreferences
  - On app launch: read from SharedPreferences and call overrideApiBaseUrl() before any network calls
  - Show a warning that auth may require LOCAL_DEVELOPMENT=true on the backend

  This is a ~50 line change that unblocks an entire class of legitimate self-hosting use cases.

**Comment by Rahulsharma0810** [comment]
Raised https://github.com/BasedHardware/omi/pull/6604 For the purposed fix.
